#-------------------------------
# Site Settings
title: Bike to explore
logo: '/images/logo/du-logo.jpg' 
description: Bike to explore
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://biketoexplore.com" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author:
  author__name: Alice
  author__bio: 
  author__avatar: ''

social:
#- {icon: "ion-logo-youtube", link: ""}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/alicegrindheim/"}




# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/



#-------------------------------
# Gallery Footer Section
gallery:
  gallery__title: Gallery
  gallery__columns: 3
  gallery__images:
    - alt: 'Rest'
      url: '/images/bayes/bayes1.jpg'
    - alt: 'Bayes'
      url: '/images/bayes/bayes2.JPG'
    - alt: 'Bayes2'
      url: '/images/bayes/bayes3.JPG'
    - alt: 'Bayes3'
      url: '/images/bayes/bayes4.jpg'
    - alt: 'Rest'
      url: '/images/bayes/du-background-img.jpg'
    - alt: 'Hobby'
      url: '/images/timeseries/ts4.jpg'
    - alt: 'Fashion'
      url: '/images/timeseries/ts2.jpeg'
    - alt: 'Notes'
      url: '/images/timeseries/ts3.jpg'
    - alt: 'Rest'
      url: '/images/timeseries/ts1.jpeg'


#-------------------------------
# Contact Settings
contact:
  email:  # Add your email for contant form
  description: 

# NOTE
# Menso theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
#disqus-identifier:  # Add your shortname for Disqus Comment. For example demo-menca


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
